version: '2'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    env_file: .env
    ports:
      - '9000:9000'
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    depends_on:
      - db

  db:
    image: mariadb
    env_file: .env
    ports:
        - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql 
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
    db-data:
        driver: local
