version: '2'
services:
 # web:
 #   build: ./web
 #   ports:
 #     - "80:80"
 #     - "443:443"
 #   depends_on:
 #     - wordpress
 #   volumes:
 #     - ./web/blog.conf:/etc/nginx/conf.d/default.conf
 #     - ./wordpress:/var/www/html
 #     - ./web/.htpasswd:/etc/nginx/htpasswd
 #     - /etc/letsencrypt/live/blog.future-search.jp:/etc/letsencrypt/live/blog.future-search.jp
 # nginx-proxy:
 #   container_name: nginx-proxy
 #   build: ./web
 #   image: nginx-proxy:0.0.2
 #   ports:
 #     - "80:80"
 #     - "443:443"
 #   volumes:
 #     - ./etc/letsencrypt/:/etc/letsencrypt/
 #     - ./etc/ssl/:/etc/ssl/
 #   command: bash -c "startup.sh"
 #   restart: always
  web:
    build: ./web
    #container_name: nignx-wordpress
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web/blog.conf:/etc/nginx/conf.d/default.conf
      #- ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/var/www/html
      - /var/www/letsencrypt/live:/var/www/letsencrypt/live
      - /var/www/html/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge
    depends_on:
      - wordpress
    restart: always
    #networks:
    #  - nginxproxy_default

  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    env_file: .env
    ports:
      - '9000:9000'
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    depends_on:
      - db
    #networks:
    #  - nginxproxy_default
  db:
    image: mariadb
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    #networks:
    #  - nginxproxy_default

volumes:
    db-data:
